name: Angular Build

# {1}
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  angular:
    name: Angular Build
    runs-on: ubuntu-latest
    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions: 
      id-token: write
      contents: write
      pages: write

# Allow one concurrent deployment
    concurrency:
      group: "pages"
      cancel-in-progress: true

    strategy:
      matrix:
        node-version: [20]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      # {2}
      - name: Checkout the source code
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      # {3}
      - name: Setup Node.js $
        uses: actions/setup-node@v4.1.0
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      # {4}
      - name: Install dependencies
        run: pnpm i
      # - name: Install Chrome
      #   run: apt-get install google-chrome-stable
      # {5}
      - name: Run tests
        run: pnpm run test:ci
      # {6}
      # - name: Build
      #   run: pnpm run build --output-path docs --base-href /inte-deploy-tp1/

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      
      - name : Deploy to NPM
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name : Deploy to GitHub Pages
        run : pnpm run deploy
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}